name: Quarto Workflow

on:
  push:
jobs:
  quarto-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Quarto passo"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Data e hora
        run: date
      - name: Versão do git
        run: git --version
  quinto-job:
    runs-on: ubuntu-latest
    needs: quarto-job
    steps:
      - run: echo "Quinto passo"
      - name: Checkout
        uses: actions/checkout@v5
      - name: validação do arquivo README.md
        run: |
          if [ -f README.md ]; then
            echo "OK"
          else
            exit 1
          fi
      - name: validação do arquivo license
        run: |
          if [ -f LICENSE ]; then
            echo "OK"
          else
            exit 1
          fi
      - name: validação do arquivo .gitignore
        run: |
          if [ -f .gitignore ]; then
            echo "OK"
          else
            exit 1
          fi
